/**
 * Generated by ChatGPT, refactored by hand.
 *
 * This implementation does not check/report syntax errors.
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

void compile_line(const char *line);

int main()
{
    size_t size = 0;
    char *line = NULL;
    size_t len;
    while ((len = getdelim(&line, &size, '\n', stdin)) != -1)
    {
        compile_line(line);
    }
    free(line);
    return 0;
}

void compile_line(const char *line)
{
    const char *ptr = line;
    while (*ptr)
    {
        if (*ptr == '>')
        {
            ptr++;
            while (*ptr == ' ' || *ptr == '\t')
                ptr++; // Skip whitespace

            while (*ptr && *ptr != '\n')
            {
                if (isxdigit(ptr[0]) && isxdigit(ptr[1]))
                {
                    char hex[3] = {ptr[0], ptr[1], '\0'};
                    unsigned char byte = (unsigned char)strtol(hex, NULL, 16);
                    fwrite(&byte, 1, 1, stdout);
                    ptr += 2;
                }
                else
                {
                    ptr++; // Skip invalid characters
                }
            }
        }
        ptr++;
    }
}
